name: bluetooth_serial_android_example
description: >
  Example app demonstrating how to use the bluetooth_serial_android plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bluetooth_serial_android:
    path: ../

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1   # Compatível com Dart 2.17+

flutter:
  uses-material-design: true
