name: bluetooth_serial_android
description: Flutter plugin for Classic Bluetooth (Serial RFCOMM) on Android. Enables device scanning, pairing, connection, and serial communication.


version: 1.0.1
homepage: https://github.com/prof-ronny/bluetooth_serial_android
repository: https://github.com/prof-ronny/bluetooth_serial_android
issue_tracker: https://github.com/prof-ronny/bluetooth_serial_android/issues
topics:
  - bluetooth
  - android
  - serial
  - spp
  - communication

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0   # última versão compatível com Dart 2.17+

flutter:
  plugin:
    platforms:
      android:
        package: prof.ronny.bluetooth_serial_android
        pluginClass: BluetoothSerialAndroidPlugin
